CREATE DATABASE shop;

CREATE TABLE vinyls ( img varchar (100), type varchar(100), title varchar(100), release_title varchar(100), credit varchar(100), artist varchar(100), anv varchar(100), label varchar(100), genre varchar(100), style varchar(100), country varchar(100), year int, format varchar (100), catno varchar(100), barcode varchar(100), track varchar (500), price int, id SERIAL);

INSERT INTO vinyls ( img, type, title, release_title, credit, artist, anv, label, genre, style, country, year, format, catno, barcode, track, price ) VALUES ( 'https://i.imgur.com/M3gFeNf.jpg',  'release', 'Nine Inch Nails - With Teeth', 'With Teeth', 'Trent Reznor & others', 'Nine Inch Nails', 'NIN', 'Nothing Records, Interscope Records', 'Electronic, Rock', 'Alternative Rock, Industrial', 'United States', '2005', 'CD, Album, Digipak', 'B0004553-01', '602498813546', 'All The Love in the World, You Know What You Are?, The Collector, The Hand That Feeds, Love Is Not Enough, Every Day Is Exactly The Same, WIth Teeth, Only, Getting Smaller, Sunspots, The Line Begins to Blur, Beside You In Time, Right Where It Belongs', '22');

INSERT INTO vinyls ( img,  type, title, release_title, credit, artist, anv, label, genre, style, country, year, format, catno, barcode, track, price ) VALUES ( 'https://i.imgur.com/u9TZjtv.jpg',  'release', 'Thievery Corporation - The Cosmic Game', 'The Cosmic Game', 'Eric Hilton, Rob Garza & others', 'Thievery Corporation', 'Thievery', 'Eighteenth Street Lounge Music', 'Electronic', 'Dub, Future Jazz, Downtempo, Latin', 'United States', '2004', 'CD, Album, Digipak, Vinyl', 'esl081', '887158874833', 'Marching the Hate Machines (Into the Sun), Warning Shots, Revolution Solution, The Cosmic Game, Satyam Shivam Sundaram, Amerimacka, Ambicion Eterna, Pela Janela, Sol Tapado, The Hearts a Lonely Hunter, Holographic Universe, Doors of Perception, Wires and Watchtowers, The Supreme Illusion, The Time We Lost Our Way, A Gentle Dissolve', '18');

INSERT INTO vinyls ( img,  type, title, release_title, credit, artist, anv, label, genre, style, country, year, format, catno, barcode, track, price )
VALUES ( 'https://i.imgur.com/wk8aWu2.jpg','release', 'The Dandy Warhols - The Dandy Warhols Come Down', 'The Dandy Warhols Come Down', 'Tony Lash', 'The Dandy Warhols', 'The Dandys', 'Tim/Kerr Records, Capitol Records', 'Electronic, Rock', 'Alternative Rock, Garage Rock, Indie Rock, Stoner Rock, Drone', 'United States', '1997', 'all', 'TK167-1, 764483-016711', '7 64483-0167 1 1', 'Be In, Boys Better, Minnesoter, Orange, I Love You, Not If You Were The Last Juniei On Earth, Every Day Should Be a Holiday, Good Morning, Whipping Tree, Green, Hard On For Jesus, Pete International Airport, The Creep Out, Cool as Kim Deal, One', '25');

INSERT INTO vinyls ( img,  type, title, release_title, credit, artist, anv, label, genre, style, country, year, format, catno, barcode, track, price )
VALUES ( 'https://i.imgur.com/bY7FRcj.jpg', 'release', 'The Cure - Disintegration', 'Disintegration', 'Robert Smith and others', 'The Cure', 'The Cure', 'Fiction Records', 'Electronic, Rock', 'New Wave, Alternative Rock', 'United Kingdom', '1989', 'LP, Album, CD', 'FIXH 14, 839 353-1', '0 42283 93531 0', 'Plainsong, Pictures of You, Closedown, Love Song, Lullaby, Fascination Street, Prayers for Rain, The Same Deep Water As You, Disintegration, Untitled', '21');

INSERT INTO vinyls ( img,  type, title, release_title, credit, artist, anv, label, genre, style, country, year, format, catno, barcode, track, price )
VALUES ( 'https://i.imgur.com/Ucw9GXt.jpg', 'release', 'Massive Attack - Mezzanine', 'Mezzanine', 'Robert Del Naja and others', 'Massive Attack', 'Massive Attack', 'Circa, Virgin', 'Electronic', 'Leftfield, Trip-Hop, Downtempo', 'Europe', '1998', 'LP, Album, CD', 'WBRLP4, 7243 8 45599 1 5', '7 24384 55991 5', 'Angel, Risingson, Teardrop, Inertia Creeps, Exchange, Dissolved Girl, Man Next Door, Black Milk, Mezzanine, Group Four, (Exchange)', '23');
